<?php
$bot = 'Unknown';

if (stristr($_SERVER['HTTP_USER_AGENT'], 'Yandex')){ $bot='Yandex';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'YandexBot')){ $bot='YandexBot';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'Yandex')){ $bot='Yandex';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'YandexDirect')){ $bot='Yandex Direct';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'Googlebot')){$bot='Googlebot';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'Google')){$bot='Google';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'Mediapartners-Google')){$bot='Mediapartners-Google (Adsense)';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'Slurp')){$bot='Hot&nbsp;Bot&nbsp;search';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'WebCrawler')){$bot='WebCrawler&nbsp;search';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'ZyBorg')){$bot='Wisenut&nbsp;search';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'scooter')){$bot='AltaVista';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'StackRambler')){$bot='Rambler';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'Aport')){$bot='Aport';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'lycos')){$bot='Lycos';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'Yahoo')){$bot='Yahoo';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'WebAlta')){$bot='WebAlta';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'yahoo')){$bot='Yahoo';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'msnbot')){$bot='msnbot/1.0';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'ia_archiver')){$bot='Alexa search engine';}
else if (stristr($_SERVER['HTTP_USER_AGENT'], 'FAST')){$bot='AllTheWeb';}


array('Google', 'Google Bot'),
        array('Gsa-crawler', 'Google Bot'),
        array('Yandex', 'Yandex Bot'),
        array('YaDirectBot', 'Yandex Direct Bot'),
        array('Yahoo', 'Yahoo Bot'),
        array('Rambler', 'Rambler Bot'),
        array('msn', 'MSN Bot'),
        array('Gigabot', 'Giga Bot'),
        array('Aport', 'Aport Bot'),
        array('Lycos', 'Lycos Bot'),
        array('FAST-WebCrawler', 'WebCrawler Bot'),
        array('Mail.Ru', 'Mail.Ru Bot'),
        array('IDBot', 'ID-Search Bot'),
        array('eStyle', 'eStyle Bot'),
        array('AbachoBOT', 'Abacho Bot'),
        array('accoona', 'Accoona Bot'),
        array('AcoiRobot', 'Acoi Bot'),
        array('ASPSeek', 'ASPSeek Bot'),
        array('CrocCrawler', 'CrocCrawler Bot'),
        array('Dumbot', 'Dumbot Bot'),
        array('GeonaBot', 'Geona Bot'),
        array('MSRBOT', 'MSR Bot'),
        array('Scooter', 'Altavista Bot'),
        array('AltaVista', 'Altavista Bot'),
        array('WebAlta', 'WebAlta Bot'),
        array('Scrubby', 'Scrubby Bot'),
        array('Slurp', 'Slurp Bot'),
        array('ia_archiver', 'IA.Archiver Bot'),
        array('Baiduspider', 'Baidu.com'),
        array('oBot', 'oBot'),
        array('Speedy Spider', 'EntireWeb Bot'),
        array('Speedy_Spider', 'EntireWeb Bot'),
        array('Teoma', 'Ask Bot'),
        array('Binky', 'libwww.Binky Bot'),
        array('amaya', 'libwww.amaya Bot'),
        array('Webgate', 'libwww.Webgate Bot'),
        array('W3C_Validator', 'libwww.W3C Validator Bot'),
        array('libwww', 'libwww.nothing Bot'),
        array('What You Seek', 'WhatYouSeek Bot'),
        array('Offline Explorer', 'Offline Explorer Bot'),
        array('Teleport', 'Teleport Bot'),
$robots = array(
	"Accoona-AI-Agent",
	"AOLspider",
	"BlackBerry",
	"bot@bot.bot",
	"CazoodleBot",
	"CFNetwork",
	"ConveraCrawler",
	"Cynthia",
	"Dillo",
	"discoveryengine.com",
	"DoCoMo",
	"ee://aol/http",
	"exactseek.com",
	"fast.no",
	"FAST MetaWeb",
	"FavOrg",
	"FS-Web",
	"Gigabot",
	"GOFORITBOT",
	"gonzo",
	"Googlebot-Image",
	"holmes",
	"HTC_P4350",
	"HTML2JPG Blackbox",
	"http://www.uni-koblenz.de/~flocke/robot-info.txt",
	"iArchitect",
	"ia_archiver",
	"ICCrawler",
	"ichiro",
	"IEAutoDiscovery",
	"ilial",
	"IRLbot",
	"Keywen",
	"kkliihoihn nlkio",
	"larbin",
	"libcurl-agent",
	"libwww-perl",
	"Mediapartners-Google",
	"Metasearch Crawler",
	"Microsoft URL Control",
	"MJ12bot",
	"T-H-U-N-D-E-R-S-T-O-N-E",
	"voodoo-it",
	"www.aramamotorusearchengine.com",
	"archive.org_bot",
	"Teoma",
	"Ask Jeeves",
	"AvantGo",
	"Exabot-Images",
	"Exabot",
	"Google Keyword Tool",
	"Googlebot",
	"heritrix",
	"www.livedir.net",
	"iCab",
	"Interseek",
	"jobs.de",
	"MJ12bot",
	"pmoz.info",
	"SnapPreviewBot",
	"Slurp",
	"Danger hiptop",
	"MQBOT",
	"msnbot-media",
	"msnbot",
	"MSRBOT",
	"NetObjects Fusion",
	"nicebot",
	"nrsbot",
	"Ocelli",
	"Pagebull",
	"PEAR HTTP_Request class",
	"Pluggd/Nutch",
	"psbot",
	"Python-urllib",
	"Regiochannel",
	"SearchEngine",
	"Seekbot",
	"segelsuche.de",
	"Semager",
	"ShopWiki",
	"Snappy",
	"Speedy Spider",
	"sproose",
	"TurnitinBot",
	"Twiceler",
	"VB Project",
	"VisBot",
	"voyager",
	"VWBOT",
	"Wells Search",
	"West Wind",
	"Wget",
	"WWW-Mechanize",
	"www.show-tec.net",
	"xxyyzz",
	"yacybot",
	"Yahoo-MMCrawler",
	"yetibot",
);

